version: "3.9"
services:
  apache:
    image: httpd:2.4
    ports:
      - "82:80"
    container_name: rapadura-apache
    restart: always
    volumes:
      - ./www:/usr/local/apache2/htdocs
    environment:
      - TZ=America/Fortaleza
      - VIRTUAL_HOST=apache.rapadura.local
    logging: 
      driver: "json-file"
      options: 
        max-size: "5m"
        max-file: "2"
    networks:
      - app
networks: 
  app:
    driver: bridge