---
    - name: Running container PHP
      hosts: 'all'
      become: yes
      become_method: sudo
      tasks:
      - name: "Launch php container"
        docker_container:
          name: rapadura-php
          image: php:7.4.24-apache-buster
          ports:
            - "81:80"
          volumes:
            - /root/php/www:/var/www/html
