---
    - name: Running container PHP
      hosts: 'all'
      become: yes
      become_method: sudo
      tasks:
      - name: "Launch database container"
        docker:
          name: rapadura-php
          rapadura-php: php:7.4.24-apache-buster
          ports:: 
            - "81:80"
          devices:
            - "./www:/var/www/html:rwm"
          env:
            TZ=America/Fortaleza
          restart: always
          networks:
            - name: "app"
          network_mode: bridge
          