---
    - name: Running container nginx
      hosts: 'all'
      become: yes
      become_method: sudo
      tasks:
      - name: "Remove dir"
        shell: rm -rf /home/ubuntu/nginx

      - name: "Remove containers"
        shell: docker rm -f rapadura-nginx
      
      - name: "Git checkout"
        ansible.builtin.git:
          repo: https://github.com/EzzioMoreira/web-rapadura.git
          dest: /home/ubuntu/nginx
          version: rapadura-nginx
          
      - name: "Run container"
        shell: docker-compose -f /home/ubuntu/nginx/docker-compose.yml up -d
