---
    - name: Running container PHP
      hosts: 'all'
      become: yes
      become_method: sudo
      tasks:
      - name: "Launch php container"
        docker_container:
          name: rapadura-php
          image: php:7.4.24-apache-buster
          exposed_ports:
            - "81:80"
          volumes:
            - ./www:/var/www/html
          env:
            TZ=America/Fortaleza
          restart: always
          networks:
            - name: "app"
          network_mode: bridge
          
