---
    - name: Install Docker
      hosts: 'all'
      become: yes
      become_user: ubuntu
      become_method: sudo
      tasks:
      - name: Instalando o Docker
        shell: curl -fsSL https://get.docker.com | bash -
      
      - name: Install packages Ubuntu
        apt:
          name: "{{ packages }}"
        vars:
          packages:
          - git
          - python3-pip

      - name: Install packages pip
        pip:
          name:
            - docker-compose
