---
    - name: Running container PHP
      hosts: 'all'
      become: yes
      become_method: sudo
      tasks:
      - name: "Remove containers"
        shell: docker rm -f rapadura-php
      
      - name: "Launch php container"
        docker_container:
          name: rapadura-php
          image: php:7.4.24-apache-buster
          restart: yes
          ports:
            - "81:80"
          volumes:
            - /root/php/www:/var/www/html
    
      - name: Git checkout
        ansible.builtin.git:
          repo: https://github.com/EzzioMoreira/web-rapadura.git
          dest: /root/php/
          version: rapadura-php
