---
    - name: Running container PHP
      hosts: 'all'
      become: yes
      become_method: sudo
      tasks:
      - name: "Remove containers"
        shell: docker rm -f rapadura-nginx
      
      - name: Git checkout
        ansible.builtin.git:
          repo: https://github.com/EzzioMoreira/web-rapadura.git
          dest: /root/nginx/
          version: rapadura-nginx
          
      - name: "Launch nginx container"
        docker_container:
          name: rapadura-nginx
          image: nginx:1.17.10
          restart: yes
          ports:
            - "80:80"
          volumes:
            - /root/nginx/nginx-conf/nginx.conf:/etc/nginx/nginx.conf
          networks:
            - name: app
          network_mode: bridge
